#!/bin/sh

npm run build
mkdir /tmp/svelte-live-chat
cp -R public/* /tmp/svelte-live-chat
git checkout .
git checkout gh-pages
rm README.md package-lock.json package.json rollup.config.js 
rm -Rf public/ src/ scripts/
cp -R /tmp/svelte-live-chat/* ./
git add .
git commit -m "Publishing docs for $(git log -1 --pretty=%B)"
git push origin gh-pages
git checkout master